server:
  port: 8080



spring:
  application:
    name: finance-boot
  # redis 配置不写，则会使用默认配置
  redis:
    database: 0
    host: 192.168.14.2
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FinanceHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.14.2:3306/finance?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      p6spy: true

mybatis-plus:
  type-aliases-package: com.luoguohua.finance.**.po
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

logging:
  level:
    com.luoguohua.finance: DEBUG
  file:
    path: D://${spring.application.name}/logs

justauth:
  enabled: true
  type:
    qq:
      client-id: 10******85
      client-secret: 1f7d************************d629e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/qq/callback
    github:
      client-id: 2d25******d5f01086
      client-secret: 5a2919b************************d7871306d1
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/github/callback
    wechat:
      client-id: wxdcb******4ff4
      client-secret: b4e9dc************************a08ed6d
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat/callback
    google:
      client-id: 716******17-6db******vh******ttj320i******userco******t.com
      client-secret: 9IBorn************7-E
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/google/callback
    microsoft:
      client-id: 7bdce8******************e194ad76c1b
      client-secret: Iu0zZ4************************tl9PWan_.
      redirect-uri: https://oauth.xkcoding.com/demo/oauth/microsoft/callback
    mi:
      client-id: 288************2994
      client-secret: nFeTt89************************==
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/mi/callback
    wechat_enterprise:
      client-id: ww58******f3************fbc
      client-secret: 8G6PCr00j************************rgk************AyzaPc78
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat_enterprise/callback
      agent-id: 1*******2
  cache:
    type: redis
    prefix: 'FEBS::CLOUD::SOCIAL::STATE::'
    timeout: 1h


finance:
  frontUrl: http://localhost:9527
  auth:
    socialLoginClientId: app
#    accessTokenValiditySeconds: 86400
#    refreshTokenValiditySeconds: 86400
#    clients:
#      - client: finance
#        secret: 123456
#        grantType: password,refresh_token
#        scope: all
    code:
      enable: true
      time: 120
      width: 115
      height: 42
      length: 4
  system:
    anonUrl: /doc.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/favicon.ico,/captcha
    swagger:
      author: luoguohua
      basePackage: com.luoguohua.finance.boot,com.luoguohua.finance.system
      description: Finance API.
      email: luoguohua_163@qq.com
      license: Apache 2.0
      licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
      title: Finance API.
      url: https://luoguohua.github.io/
      version: 1.0