server:
  port: 8080



spring:
  application:
    name: finance-boot
  # redis 配置不写，则会使用默认配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

finance:
  auth:
    accessTokenValiditySeconds: 86400
    refreshTokenValiditySeconds: 86400
    clients:
      - client: finance
        secret: 123456
        grantType: password,refresh_token
        scope: all